language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required

before_install:
  - sudo apt-get -q update
  - sudo apt-get -y install p7zip-full libglib2.0-dev:i386 libgl1-mesa-dev:i386 libasound2-dev:i386 libpulse-dev:i386 libjpeg-dev:i386 libsdl2-dev:i386 libcurl4-openssl-dev:i386
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install gcc-8 g++-8 gcc-8-multilib g++-8-multilib

script: |
  cd $TRAVIS_BUILD_DIR/src
  mkdir $TRAVIS_BUILD_DIR/src/build
  cd $TRAVIS_BUILD_DIR/src/build

  export CC="gcc-8 -m32"
  export CXX="g++-8 -m32"
  cmake -DCMAKE_BUILD_TYPE=Release -DUSE_SDL2=TRUE -DCMAKE_TOOLCHAIN_FILE="../cmake/toolchains/linux-i686.cmake" ..
  cmake --build . --config Release"
  export TZ='America/Chicago'
  build_date=date +%Y-%m-%d
  7z a "$build_date.zip" ete.x86 ete-ded.x86
  7z a "$build_date.zip" ../../docs/*

# - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis-linux-cmake.sh; fi
# - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis-linux.sh; fi
# - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./travis-macos.sh; fi

#deploy:
#  provider: releases
#  file_glob: true
#  skip_cleanup: true
#  draft: true
#  prerelease: false
#  api_key:
#    secure: "n5NzbUHEvac0eXKCMoFxb/AUftv/Y2RD6cOwLvq8opBhw809ekbiCS2rUh3WYHzYsa0DKgWUrOtJWT9mWv1ySaoEPuo0Dl+YHriH/nupBzVbNUCF64Bz51hLl9LOANlP/uuCeRih3r6a2QvKG1oSf/OtLp2rhkWLS6zhyj3tnbnyPdONaxCwyY4QOWJY1nBJa7YPQ20yIWs0L1bKFXpJC+IDqz6R65a1s3tgLmnQrmIOlPgfRZtiXBrO47LZlGhe3NEZOgXtr1ar8kK4SwK6w23ykSJIen9Jh48jj96ZUSdQvEuMVTUYzfyPvnDaIzkA7ChhKn6BKb8/dHQ+JD7s81Wz2wBU0RuE63nLszQVS8LFK5NgRtyWr9YpuY+IHlPjZPP1n4OukJ9FNkANf0Z+wZVhk847xVcjkjMu3ZahpKxn+2L5lyIOOF1L1NGt/WqGLPVmZ4rw8EwP44+zb9SXowe3KmTQcMi6ShD/6RKiubpxeuHvwNlIhP8X/se90sqttBb4fUohf57U5/Fu1nzBwYGolDON4V19JH0Uvqq5nr0Es8J96ckHXI5dwIMrrNkjlGgvCnQ+03eKcY3wtFMC/aVfLh+mZl5EUA3YwzYJu39GYZ6KmOi4Cjq9j23wmp+QLdTr+0jXUrVgQumJyb/zV8P87WbTvYvvQviyc+cHHA0="
#  file: "ete*.7z"
#  on:
#    tags: true

notifications:
  email: false
