version: ETe-{branch}-{build}
image: Visual Studio 2017
configuration: Release

#environment variable version
environment:
  BUILD_CONFIGURATION: Release

# custom build script to specify xp mode and listed configuration
# wolf.sln currently only has the projects included that are built due to difficulty of making it only build ones we want on appveyor
build_script:
  - cmd: call appveyor.bat
artifacts:
  - path: wolfet*.zip
deploy:
 description: ''
 provider: GitHub
 auth_token:
   secure: 'ocTqqbL+j4fZepSEpb1U76avHU0R/58qH9m2pTtgFGPHbIop7Pu6GLifZSnQm0Ym'
 draft: true
 prerelease: false
 on:
  appveyor_repo_tag: true
